### ISSUE TITLE
Be able to add and remove self from classes (as a tutor)

### ISSUE THREAD

**Issue by AlexisDougherty13** [WillBAnders/TutorsVILLE#78]
If you are the tutor who is logged in, show the minus button on your box if your name comes up in /courses/:code. Else, show a plus to add yourself

**Comment by AlexisDougherty13** [comment]
Backend role: Add and del from DB

**Comment by AlexisDougherty13** [comment]
Routes:
/courses/:code/:username/add
/courses/:code/:username/remove

**Comment by WillBAnders** [comment]
Mentioned in the PR, the routes for this should use a CRUD style API and work off the authenticated user. It's better to scope this to the tutor rather than the course, but I also like the idea of having a dedicating `tutoring` route matching the backend as in:

 - POST `/tutoring/:code` (add)
 - DELETE `/tutoring/:code` (remove)
